defaultmodelacc/urls.py
from django.urls import path

from property.views import OwnerCreateView

urlpatterns = [
    path('signup/', OwnerCreateView.as_view(), name='signup'),
]

home_rent/urls.py
from django.contrib import admin
from django.urls import path, include
from property import urls as property_urls
from defaultmodelacc import urls as acc_urls
from django.contrib.auth import urls as django_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(property_urls)),
    path('accounts/', include(django_urls)),
    path('accounts/', include(acc_urls)),
]

property/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django_filters.views import FilterView

from property import views
from property.models import Home
from property.views import HomeCreateView

urlpatterns = [
    path('', views.product_list, name='home'),
    path('home/<int:pk>/', views.HomeDetailView.as_view(), name='home_detail'),
    path('update/<int:pk>/', views.HomeUpdateView.as_view(), name='home_update'),
    path('create/', HomeCreateView.as_view(), name='home_create'),
    path('delete/<int:pk>/', views.HomeDeleteView.as_view(), name='home_delete'),
    path('owners/', views.OwnerListView.as_view(), name='owners'),
    path('newowner/', views.OwnerCreateView.as_view(), name='owner_create'),
    # url(r'^list/$', FilterView.as_view(model=Home)),
    # path('filter/', views.product_list, name='filters'),
]

defaultmodelacc/models.py
from django.db import models

# Create your models here.

property/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse

from defaultmodelacc.views import SignUpView


class Home(models.Model):
    area = models.PositiveIntegerField(blank=True, null=False)
    address = models.CharField(max_length=300)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50, default='Albania')
    rent = models.PositiveIntegerField(blank=False)
    owner = models.ForeignKey(
        'Owner',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.city + ' ' + self.state

    def get_absolute_url(self):
        return reverse('home')


class Owner(models.Model):
    user = models.OneToOneField(  # change to models.OneToOneField
        'auth.User',
        on_delete=models.CASCADE, related_name='owner'
    )
    phone = models.IntegerField(verbose_name='Phone number')

    def __str__(self):
        return self.user.username

property/forms.py
from django import forms
from django.forms import ModelForm
from django.template import loader, RequestContext

from property.models import Owner, Home


class HomeForm(ModelForm):
    # fields = ['area', 'address', 'city', 'state', 'rent', 'owner']
    class Meta:
        model = Home
        # fields = '__all__'
        fields = ['area', 'address', 'city', 'state', 'rent']
    # area = forms.IntegerField(min_value=0)
    # address = forms.CharField(max_length=100)
    # city = forms.CharField(max_length=20)
    # state = forms.CharField(max_length=20)
    # rent = forms.IntegerField(min_value=0)
    # owner = forms.Select(choices=Owner.objects.filter())


class OwnerForm(ModelForm):
    class Meta:
        model = Owner
        fields = ['username', 'first_name', 'last_name', 'phone', 'email', 'password1']
    username = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.CharField(max_length=40)
    password1 = forms.CharField(max_length=20)

defaultmodelacc/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    # /home_rent/venv/lib64/python3.7/site-packages/django/contrib/auth/forms.py
    success_url = reverse_lazy('login')
    template_name = 'signup.html'
    # fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']
    # def form_valid(self, form):
    #     """If the form is valid, save the associated model."""
    #     self.object = form.save(commit=False)
    #     self.object.author = self.request.user
    #     self.object.save()
    #     return super().form_valid(form)
    #
    # def form_invalid(self, form):
    #     pass

property/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django_filters.views import BaseFilterView

from property.filters import HomeFilter
from property.forms import HomeForm, OwnerForm
from property.models import Home, Owner


class HomeListView(ListView, BaseFilterView):
    model = Home
    template_name = 'home.html'
    filterset_class = HomeFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['home'] = Home.objects.filter()
        context['filter'] = HomeFilter
        return context

    @staticmethod
    def product_list(request):
        f = HomeFilter(request.GET, queryset=Home.objects.all())
        return render(request, 'home.html', {'filter': f})


class OwnerListView(ListView):
    model = Owner
    template_name = 'owners.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['home'] = Home.objects.filter()
        context['owner'] = Owner.objects.filter()
        return context


class HomeDetailView(DetailView):
    model = Home
    template_name = 'home_details.html'


class HomeUpdateView(UpdateView):
    model = Home
    template_name = 'home_update.html'
    fields = ['area', 'address', 'city', 'state', 'rent']
    context_object_name = 'updatehome'


class HomeCreateView(CreateView):
    model = Home
    template_name = 'home_update.html'
    form_class = HomeForm
    context_object_name = 'createhome'

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        self.object.owner = self.request.user.owner
        self.object.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        pass


class HomeDeleteView(DeleteView):
    template_name = 'home_delete.html'
    model = Home
    context_object_name = 'deletepost'
    success_url = reverse_lazy('home')


def product_list(request):
    f = HomeFilter(request.GET, queryset=Home.objects.all())
    return render(request, 'home.html', {'filter': f})


class OwnerCreateView(CreateView):
    model = Owner
    form_class = OwnerForm
    template_name = 'signup.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save(commit=False)
        user = User(
            username=form.cleaned_data['username'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            email=form.cleaned_data['email'],
        )
        user.set_password(form.cleaned_data['password1'])
        user.save()
        self.object.user = user
        self.object.save()
        return super().form_valid(form)
        # self.object = form.save(commit=False)
        # self.object.first_name = User.username
        # self.object.last_name = User.last_name
        # self.object.email = User.email
        # self.object.save()
        # return super().form_valid(form)

    def form_invalid(self, form):
        pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 50%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    input[type=text], input[type=number], select {
        width: 25%;
        padding: 8px 10px;
        margin: 8px 0;
        display: inline-block;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    input[type=submit] {
        width: 25%;
        background-color: lightgreen;
        color: black;
        padding: 8px 10px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    input[type=submit]:hover {
        background-color: #ccc;
    }

    div {
        border-radius: 5px;
        background-color: white;
        {#padding: 20px;#}
        padding-bottom: 10px;
    }
    .first{
        background-color: black;
        color: white;
    }

    .new{
        color: white;
    }
</style>
<head>
    <title>Django app</title>

</head>
<body>
<header>
    <h1><a href="{% url 'home' %}">Listings</a></h1>
</header>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
</body>
</html>

templates/filter.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="get">
        {# ['area', 'address', 'city', 'state', 'rent', 'owner'] #}
        <p>Owner</p>
        {{ filter.form.owner }}
        <p>Area</p>
        {{ filter.form.area }}
        <p>City</p>
        {{ filter.form.city }}
        <p>State</p>
        {{ filter.form.state }}
        <p>Address</p>
        {{ filter.form.address }}
        <p>Price</p>
        <div class="new">
            {{ filter.form.rent }}
        </div>
        <br>
        <input type="submit"/>
    </form>
    <br>
    <h2>Results:</h2>
    <table>
        <tr>
            <th>Address</th>
            <th>Rent</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
            <th>View</th>
            {% for obj in filter.qs %}
                {#        <a href="{% url 'home_detail' obj.id %}">City: {{ obj.city }} - Rent: ${{ obj.rent }}</a><br/>#}
                <tr>
                    <td style="text-align: left;">{{ obj.address }}</td>
                    <td>{{ obj.rent }}</td>
                    <td><a href="{% url 'owners' %}">{{ obj.owner }}</a></td>
                    <td><a href="{% url 'home_update' obj.id %}">+ update rental</a></td>
                    <td><a href="{% url 'home_delete' obj.id %}">+ delete rental</a></td>
                    <td><a href="{% url 'home_detail' obj.id %}">+ view rental</a></td>
                </tr>
            {% endfor %}
    </table>
{% endblock %}

templates/home.html
{% extends 'base.html' %}


{% block content %}
    <div style="text-align: right">
        {% if user.is_authenticated %}
            hi, {{ user.username }}
            <p><a href="{% url 'logout' %}">logout</a></p>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">login</a> |
            <a href="{% url 'signup' %}">signup</a>
        {% endif %}
    </div>
    <form action="" method="get">
        {# ['area', 'address', 'city', 'state', 'rent', 'owner'] #}
        <p>Price</p>
        <div class="new">
            {{ filter.form.rent }}
        </div>
        <p>Owner
            {{ filter.form.owner }}
            Area
            {{ filter.form.area }}
        </p>

        <p>City
            {{ filter.form.city }}
            State
            {{ filter.form.state }}
        </p>

        <p>Address
            {{ filter.form.address }}
        </p>
        <input type="submit"/>
    </form>
    <br>
    <table>
        <tr>
            <th>Address</th>
            <th>Rent</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
            <th>View</th>
        </tr>
        {% for obj in filter.qs %}
            {#        {% for obj in filter.qs %}#}
            <tr>
                <td style="text-align: left;">{{ obj.address }}</td>
                <td>{{ obj.rent }}</td>
                <td><a href="{% url 'owners' %}">{{ obj.owner }}</a></td>
                {% if obj.owner.user.username == request.user.username %}
                    <td><a href="{% url 'home_update' obj.id %}">+ update rental</a></td>
                    <td><a href="{% url 'home_delete' obj.id %}">+ delete rental</a></td>
                {% else %}
                    <td>- update rental</td>
                    <td>- delete rental</td>
                {% endif %}

                <td><a href="{% url 'home_detail' obj.id %}">+ view rental</a></td>
            </tr>
        {% endfor %}
    </table>

    <p><a href={% url 'home_create' %}>+ create new rental</a></p>
    {#    <p><a href="{% url 'filters' %}">+ filter rentals</a></p>#}
    <br>

{% endblock content %}

templates/home_delete.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete this rental?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

templates/home_details.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div>
            <h2>Owner:</h2>
            {{ home.owner }}
        </div>
        <div>
            <h3>Area:</h3>
            {{ home.area }}
            <h3>Address:</h3>
            {{ home.address }}
        </div>
        <div>
            <h3>City:</h3>
            {{ home.city }}
            <h3>State:</h3>
            {{ home.state }}
        </div>
        <div>
            <h3>Rent:</h3>
            {{ home.rent }}
        </div>
    </div>
{% endblock content %}

templates/home_update.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <form method="post" action={% url 'home_update' object.id %}>{% csrf_token %}
    {% else %}
        <form method="post" action={% url 'home_create' %}>{% csrf_token %}
    {% endif %}


{# ['area', 'address', 'city', 'state', 'rent', 'owner'] #}
{#<div>#}
{#    {{ form.owner.label_tag }}#}
{#    {{ form.owner }}#}
{#    {{ form.owner.errors }}#}
{#</div>#}
<div>
    {{ form.area.label_tag }}
    {{ form.area }}
    {{ form.area.errors }}
    {{ form.address.label_tag }}
    {{ form.address }}
    {{ form.address.errors }}
</div>
<div>
    {{ form.city.label_tag }}
    {{ form.city }}
    {{ form.city.errors }}
    {{ form.state.label_tag }}
    {{ form.state }}
    {{ form.state.errors }}
</div>
<div>
    {{ form.rent.label_tag }}
    {{ form.rent }}
    {{ form.rent.errors }}
</div>
{% if object %}
    <input type="submit" value="Update">
{% else %}
    <input type="submit" value="Create">
{% endif %}
</form>


{% endblock %}

templates/owners.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Phone</th>
            <th>Email</th>
        </tr>
        {% for owner in owner_list %}
            <tr>
                <td>{{ owner.user.first_name }}</td>
                <td>{{ owner.user.last_name }}</td>
                <td>{{ owner.phone }}</td>
                <td>{{ owner.user.email }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <h2>Sign Up</h2>
    <form method="post"> {% csrf_token %}
                {{ form.as_p }}
{#        {{ form.first_name.label_tag }}#}
{#        {{ form.first_name }}#}
{#        {{ form.first_name.errors }}#}
{##}
{#        {{ form.last_name.label_tag }}#}
{#        {{ form.first_name }}#}
{#        {{ form.first_name.errors }}#}
{##}
{#        {{ form.first_name.label_tag }}#}
{#        {{ form.first_name }}#}
{#        {{ form.first_name.errors }}#}
{##}
{#        {{ form.first_name.label_tag }}#}
{#        {{ form.first_name }}#}
{#        {{ form.first_name.errors }}#}
{##}
{#        {{ form.first_name.label_tag }}#}
{#        {{ form.first_name }}#}
{#        {{ form.first_name.errors }}#}
        <button type="submit">Sign Up</button>
    </form>
{% endblock %}